#!/usr/bin/env bash

access_log="/var/log/apache2/access.log"

# check for 4xx errors and output to the screen
echo "4xx errors:"

if ! sudo egrep '\s4[0-9]{2}\s' "$access_log";
then
  echo "Not found"
fi

# check for 5xx errors and output to the screen
echo "5xx errors:"

if ! sudo egrep '\s5[0-9]{2}\s' "$access_log";
then
  echo "Not found"
fi